// app/layout.tsx
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import AppShell from './AppShell';
import { Toaster } from 'react-hot-toast';
// import { useSearchParams } from 'next/navigation';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Test project',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // useSearchParams faqat Client Componentda ishlaydi, shuning uchun
  // agar siz layoutni Client Component qilmoqchi bo'lsangiz
  // 'use client' qo'shishingiz kerak
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <Toaster position="top-right" />
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
